name: Feature request
description: Suggest an idea or improvement for lucent-flow
body:
  - type: checkboxes
    attributes:
      label: Is this suited for GitHub?
      description: Join the discussion in our [community forum](https://discord.gg/lucent-flow) for quicker responses or brainstorming ideas.
      options:
        - label: Yes, this is suited for GitHub
  - type: markdown
    attributes:
      value: |
        Use this template to suggest a feature or improvement for lucent-flow.

        Bug reports should be submitted using the [Bug Report Template](https://github.com/abaymimi/lucent-flow/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).

        Before submitting a feature request, please check the [existing issues](https://github.com/abaymimi/lucent-flow/issues) and :+1: upvote similar requests. This helps prioritize features based on community interest.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Provide a clear and concise description of the problem. For example, "I'm frustrated when..."
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: Provide a clear and concise description of what you want to achieve with this feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Provide a clear and concise description of alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or references to support your feature request.
